### ISSUE TITLE
Nano Emacs does not work well with mu4e's latest stable release

### ISSUE THREAD

**Issue by Adocentyn** [rougier/nano-emacs#94]
Since mu/mu4e 1.6.x branch has been released I'm getting this error message at emacs startup:
`error: Invalid face, mu4e-moved-face
`
As and additional symptom, mu4e no longer finds the basic setup of its accounts or contexts and defaults to nicolas rougier as the only account. Looking at the config file for nano-mu4e I was not able to understand what I could do to change that behaviour (same as the default settings file for nano.

**Comment by rougier** [comment]
Thanks  for the report I did not get the problem for some reason. Could you try the [nano-theme](https://github.com/rougier/nano-theme) as a stand-alone theme to see if it solves the problem?

**Comment by rougier** [comment]
Also, the nano-theme should be more robust since it is a real theme and should cope with non-defined faces.

**Comment by Adocentyn** [comment]
I tried to do just that, both with nano-theme and nano-theme-dark. Both packages are on my machine. Yet for some strange reason they won't load - I get an error message that the package cannot be found. Is this the crux of the issue?

**Comment by rougier** [comment]
For `nano-theme`, this is a regular theme and you should be able to load it as a theme or you can use:

```
(require 'nano-theme)
(nano-dark)
```

**Comment by Adocentyn** [comment]
Thank you, it did work.

**Comment by seblemaguer** [comment]
Hello,

I am not sure it is solved. `mu4e-moved-face` is not defined in the last release (1.6) of mu. It is also the case for the functions prefixed by `mu4e~` which have been either refactored or renamed with the prefix `mu4e-`.  This last bit impacts `nano-modeline`. I can do a pull request for this but @rougier I don't wan't to corrupt your setup if you are using a version of mu4e < 1.6.

**Comment by Adocentyn** [comment]
I closed the issue as it worked for me with the suggested fix, but I do understand it's all quite experimental and that the fix does not actually solve the issue for all cases (you need to stick to the provided theme, or else). On top of this @rougier was not able to replicate it. Should we leave this one closed and open a new one, possibly with a patch committed as a result?

**Comment by rougier** [comment]
@seblemaguer I've switched to 1.6.5 and I did not notice the problem. Note that I use [nano-modeline](https://github.com/rougier/nano-emacs/blob/master/nano-modeline.el) here. But please proceed with the PR such that I can check why it's working for me (maybe I changed it and forgot to commit)

**Comment by rougier** [comment]
@Adocentyn I think the best way would be to use nano theme. I need to refactor the nano-emacs README because I've tried to split each module with its own git repo and the ones inside nano-emacs are not up to date.

**Comment by seblemaguer** [comment]
@rougier ok :) I do this asap
